### ISSUE TITLE
Looking for firmware for original Kobo N416 1.8.3

### ISSUE THREAD

**Issue by tonyyng** [pgaskin/KoboStuff#5]
Firmware 1.8.3 r22907 Dec 30, 2010

**Comment by pgaskin** [comment]
I've responded on MobileRead. For convenience, here is the link: https://send.geek1011.net/download/7ba9f980cf/#Rnd7bfoWICppvD4ZS4oL2Q .

**Comment by tonyyng** [comment]
Replied on the Mobileread forum.  I found the same file at http://download.kobobooks.com/firmwares/kobo/kobo-upgrade-1.8.zip.

However, I wasn't able to do anything that made the reader do anything with it.

Do you have a file called: kobo-sd-restore-1.8.tgz?

**Comment by pgaskin** [comment]
No, but there are two ways to sideload the older firmware updates. IIRC, you can either boot it off a SD card (for testing updates) or you can hold the power and menu buttons to get it into update mode (and then you can copy the file).

**Comment by pgaskin** [comment]
And in response to your point on MobileRead about it not looking like other firmware updates, this is because the update process is slightly different on older Kobo readers. From what I discovered while experimenting (I don't actually have an original Kobo, and I didn't do Kobo stuff at that time), the update contains a filesystem image containing a base YAFFS image with a basic Linux system which then extracts the Kobo software into the usr directory. In relation to the newer update format, the base image appears to be equivalent to the recovery partition and the usr tarball appears to be equivalent to the KoboRoot.tgz
